[package]
name = "world_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs" # 这个路径得有 用于包wasm

[dependencies]
wasm-bindgen = "0.2.83"
